services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=en,hi,kn,te,ta
    restart: unless-stopped
